version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
