name: flutter_quizzer
description: A quiz app to test your knowledge of basic flutter concepts.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  meta: ^1.16.0
  questions_repository:
    path: packages/questions_repository/

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/
