name: questions_repository
description: A repository of questions for Flutter Quizzer.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
dependencies:
  equatable: ^2.0.7
