name: flutter_quizzer

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  
  paths:
      - 'lib/**'
      - '*.yaml'
      - 'packages/**/lib/**'
      - 'packages/**/*.yaml'

  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          customArgs: --target='lib/main_development.dart'
          # customArgs: -t lib/main_development.dart #likely also works
          baseHref: /flutter-quizzer/
